# Generated by Django 3.2.16 on 2023-04-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0002_rename_stuff_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='inst',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='tg',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='vk',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
