# Generated by Django 3.2.16 on 2023-04-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0003_auto_20230405_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='inst',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='tg',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='vk',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
