# Generated by Django 3.2.16 on 2023-04-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0004_auto_20230414_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='avatar',
            field=models.ImageField(upload_to='avatar/stuff/%Y/%m/%d/', verbose_name='Фото профиля'),
        ),
    ]
