# Generated by Django 3.2.16 on 2023-04-02 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project_01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_01',
            name='my_profession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_role', to='Project_01.professions'),
        ),
        migrations.RemoveField(
            model_name='project_01',
            name='looking_for',
        ),
        migrations.AddField(
            model_name='project_01',
            name='looking_for',
            field=models.ManyToManyField(related_name='looking_for', to='Project_01.Professions'),
        ),
    ]
