# Generated by Django 3.2.16 on 2023-04-02 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project_01', '0002_auto_20230402_1402'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageModel',
            new_name='ImageProject01',
        ),
    ]
