# Generated by Django 3.2.16 on 2023-04-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_01', '0003_rename_imagemodel_imageproject01'),
    ]

    operations = [
        migrations.AddField(
            model_name='professions',
            name='link',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
