# Generated by Django 3.2.16 on 2023-04-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_01', '0006_alter_project_01_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmember',
            name='is_invited',
            field=models.BooleanField(default=False),
        ),
    ]
