# Generated by Django 3.2.16 on 2023-03-27 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Photographers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albumph',
            old_name='user',
            new_name='owner',
        ),
    ]
