# Generated by Django 3.2.16 on 2023-04-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Photographers', '0004_alter_commentph_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='avatar',
            field=models.ImageField(upload_to='avatar/ph/%Y/%m/%d/', verbose_name='Фото профиля'),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='inst',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='tg',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='vk',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
