# Generated by Django 3.2.16 on 2023-04-14 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project_01', '0005_projectmember_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('status', models.CharField(default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_whom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invites', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project_01.project_01')),
                ('role', models.ManyToManyField(to='Project_01.Professions')),
                ('whom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='got_invites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
