# Generated by Django 3.2.16 on 2023-04-15 07:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Project_01', '0006_alter_project_01_owner'),
        ('Notifications', '0002_invite'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invite',
            unique_together={('project', 'whom')},
        ),
    ]
