# Generated by Django 3.2.16 on 2023-04-15 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project_01', '0006_alter_project_01_owner'),
        ('Notifications', '0004_rename_text_invite_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='role',
        ),
        migrations.AddField(
            model_name='invite',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Project_01.professions'),
        ),
    ]
