# Generated by Django 3.2.16 on 2023-03-25 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0004_alter_commentmodel_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albummodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='Models.model'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='Models.model'),
        ),
    ]
