# Generated by Django 3.2.16 on 2023-03-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0008_alter_imagemodel_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
