# Generated by Django 3.2.16 on 2023-04-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0009_alter_commentmodel_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='avatar',
            field=models.ImageField(upload_to='avatar/model/%Y/%m/%d/', verbose_name='Фото профиля'),
        ),
    ]
