# Generated by Django 3.2.16 on 2023-04-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0011_auto_20230414_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='bust',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Обхват груди'),
        ),
        migrations.AlterField(
            model_name='model',
            name='hips',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Обхват бедер'),
        ),
        migrations.AlterField(
            model_name='model',
            name='shoe_size',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Размер ноги'),
        ),
        migrations.AlterField(
            model_name='model',
            name='waist',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Обхват талии'),
        ),
    ]
