# Generated by Django 3.2.16 on 2023-04-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0012_auto_20230414_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='tattoo',
            field=models.BooleanField(default=False, verbose_name='Наличие тату'),
        ),
    ]
