# Generated by Django 3.2.16 on 2023-04-17 15:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_chatgroup_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalChatGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('owner_name', models.CharField(max_length=255)),
                ('view_name', models.CharField(max_length=255)),
                ('members', models.ManyToManyField(related_name='personal_chat_group', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
