# Generated by Django 3.2.16 on 2023-04-17 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_personalchatgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('chat_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.personalchatgroup')),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
    ]
