# Generated by Django 3.2.16 on 2023-04-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_personalmessage_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalchatgroup',
            name='owner_name',
            field=models.CharField(default='owner_name', max_length=255),
        ),
        migrations.AlterField(
            model_name='personalchatgroup',
            name='view_name',
            field=models.CharField(default='view_name', max_length=255),
        ),
    ]
