# Generated by Django 3.2.16 on 2023-04-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20230421_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='new',
            field=models.BooleanField(default=True),
        ),
    ]
