# Generated by Django 3.2.16 on 2023-04-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Locations', '0002_auto_20230417_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='time_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
