# Generated by Django 3.2.16 on 2023-04-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='text',
        ),
        migrations.AddField(
            model_name='note',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
