# Generated by Django 3.2.16 on 2023-04-04 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project_01', '0005_projectmember_link'),
        ('Calendar', '0004_auto_20230404_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='project_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Project_01.project_01'),
        ),
    ]
